spring.application.name=weather

# Puerto del servidor
server.port=8080

# Configuración de Caché (Caffeine)
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=24h,maximumSize=1000

# Configuración de OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Aumentar timeouts de Feign porque el endpoint de municipios de AEMET es masivo y lento
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=60000

# Credenciales de acceso a la API (Para Basic Auth)
api.security.username=${API_USERNAME:admin}
api.security.password=${API_PASSWORD}

# Configuración del Cliente AEMET
aemet.api.key=${AEMET_API_KEY}
